export const USERS = {
  FETCH_SUCCESS: 'USERS_FETCH_SUCCESS',
  FETCH_FAILED: 'USERS_FETCH_FAILED'
}

export const POSTS = {
  FETCH_SUCCESS: 'POSTS_FETCH_SUCCESS',
  FETCH_FAILED: 'POSTS_FETCH_FAILED'
}

export const COMMENTS = {
  FETCH_SUCCESS: 'COMMENTS_FETCH_SUCCESS',
  FETCH_FAILED: 'COMMENTS_FETCH_FAILED'
}

